### ISSUE TITLE
Use custom JS instead of default one

### ISSUE THREAD

**Issue by Humorist2601** [anemomylos/shell4kbin#2]
Hello, really appreciate the app you have developed but I have just one thing stopping me from using the app completely

So I want to use the [Kbin Enhancement Suite](https://aclist.github.io/kes/kes.html) but it doesn't work one a straight copy paste. Can you guide me on how to make it work in this app?

**Comment by anemomylos** [comment]
Hi.
In order to test it, can you tell me something that is changed when you install this JS?

In general, in order to activate the injected JS code, you have to enable the switch on top (“Inject JS”) and press the “Save code” button to save any changes on the code.

**Comment by Humorist2601** [comment]
There should be a wrench appear on the top right corner for configuring the script

I copy pasted both the Kbin Enhancement Suite aswell as the Kbin Enhancement Script but both didn't work. I compared the original Enhancement Script with yours and they both are different so I think it has go to do something with that

![example](https://github.com/anemomylos/shell4kbin/assets/97790626/3f262b4c-f5e2-4269-a7ba-747e0e734eb2)

**Comment by anemomylos** [comment]
From what I understand, it is not possible to have KES injected as is. KES is an interface to load the other scripts defined in the "@require" variables and needs the "*Monkey" addon installed in the browser to start properly.
I cannot say whether the developer of KES can modify it so that it is injected directly without needing the "Monkey" addon; you might ask him if this is possible.

Btw the default JS is not mine, I found a link about it in a kbin post, you can find the original source code at https://greasyfork.org/en/scripts/468612-kbin-enhancement-script/code - there is also a comment in the code about the source.

**Comment by anemomylos** [comment]
It will not be possible to implement this request because it is beyond the current scope of the app.

**Comment by anemomylos** [comment]
It will not be possible to implement this request because it is beyond the current scope of the app.

**Comment by anemomylos** [comment]
It will not be possible to implement this request because it is beyond the current scope of the app.
